### Get Products
GET http://localhost:3003/products

### Get Product By Id
GET http://localhost:3003/products/1

### Create an order
POST http://localhost:3003/orders
Content-Type: application/json

{
    "userName": "teste novo mais uma vez",
    "deliveryDate": "2022-10-05",
    "products": [
        {
            "id": 16,
            "quantity": 1
        },
        {
            "id": 18,
            "quantity": 1
        }

    ]
}

### Admin Login
POST http://localhost:3003/users/adminLogin
Content-Type: application/json

{
    "email": "user_admin@gmail.com",
    "password": "qwerty00"
}